### PR TITLE
Fill_detail usecase

### PR DESCRIPTION
**Pull request by Dennis-Ding1**
Hi guys. Just complete Fill_deatil usecase.

This usecase allows use to see details of results of ModelDB and NeuroElectro database. Because as I mention in DAOs, these two can't give us details of models at once. By doing this, we can reduce the request needs to be sent to sever.

Now I only implement it to support Query for detail button in the search view. But I think I can make it to support star view simultaneously. I'll add that on if I find it practical.

### CODE REVIEW

**Review by DonuttDog — CHANGES_REQUESTED** [review]
Overall, it's a great implement of feature fill_detail.

Coding style is nice, used a consistent style with others, following most the convention and the same structure.

The main logic is pretty good, but **seems like you forget to add one case in the ScrollResultPanel.propertyChange()** (Only modified the view_model)

You didn't provide Tests here, but I know you will do them when other parts are done, just don't forget to do this later.

It is strictly followed with CA engine, and thus there are many SOILD Principles show up, which every layer is isolated.

Maybe add some Javadoc, especially in the Interactor, will be a good idea, which will make people know what is each use_case doing.

There are enough info for us to know what you have done, nice job!

**Comment by Dennis-Ding1** [comment]
Hi guys, update:
I add a case in ScrollResultPanel.propertyChange(), thanks for pointing it out!
I also modified the interactor and presenter a little bit to support "Query for detail" to work simultaneously in search view and star view!
The tests for this use case are included now. Inteactor gets 71% line coverage because there's some IOexception catch block. The presenter will be tested in the end-to-end test. Beside it, everything works fine.

image

**Comment by MarksonChen** [comment]
Hi Dennis, you can test IOExceptions of DAOs by writing a mock DAO. Recap that it is a rubric requirement to have >90% line coverage for all interactions.

**Comment by MarksonChen** [comment]
Hi Dennis, I wrote two tests for you that handle IOExceptions.
image

Now the interactor has 100% line coverage:
image

**Pull request merged**
